name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code from the master branch
    - uses: actions/checkout@v3
    
    # Setup .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.107

    # Publish the project
    - name: Publish .NET Core Project
      run: dotnet publish src/StackNServe/StackNServe.csproj -c Release -o release --nologo
    
    # Verify that index.html exists after the publish
    - name: Verify index.html exists
      run: |
        if [ ! -f release/wwwroot/index.html ]; then
          echo "Error: index.html not found!"
          exit 1
        fi

    # Change base tag in index.html to point to the correct subdirectory (StackNServe)
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/CS455_Tinker\/" \/>/g' release/wwwroot/index.html
    
    # Copy index.html to 404.html for GitHub Pages fallback routing
    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # Add a .nojekyll file to prevent Jekyll processing
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    # Deploy the wwwroot folder to the gh-pages branch
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: src/StackNServe/release/wwwroot
